mas:
  backend:
    basePath: api.mas.backend
    detailPath:
      privateClientController: ${mas.backend.basePath}/privateClient
      corporateClientController: ${mas.backend.basePath}/corporateClient
      noviceGardenerController: ${mas.backend.basePath}/noviceGardener
      experiencedGardenerController: ${mas.backend.basePath}/experiencedGardener
      administrationWorkerController: ${mas.backend.basePath}/administrationWorker
      speciesController: ${mas.backend.basePath}/species
      undemandingPlantController: ${mas.backend.basePath}/undemandingPlant
      demandingPlantController: ${mas.backend.basePath}/demandingPlant
      gardenController: ${mas.backend.basePath}/garden
      visitController: ${mas.backend.basePath}/visit

    garden:
      name: National Botanic garden
      address: 15 avenue 30-49, Pennsylvania
      openHours: 9AM - 6PM