mas:
  backend:
    basePath: api.mas.backend
    detailPath:
      privateClientController: ${mas.backend.basePath}/privateClient
      corporateClientController: ${mas.backend.basePath}/corporateClient
      noviceGardenerController: ${mas.backend.basePath}/noviceGardener
      experiencedGardenerController: ${mas.backend.basePath}/experiencedGardener
      administrationWorkerController: ${mas.backend.basePath}/administrationWorker