mas:
  backend:
    basePath: api.mas.backend
    detailPath:
      privateClientController: ${mas.backend.basePath}/privateClient
      corporateClientController: ${mas.backend.basePath}/corporateClient